[package]
name = "tessera-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "tsr"
path = "src/main.rs"

[dependencies]
tessera-phases = { path = "../tessera-phases" }
tessera-db = { path = "../tessera-db" }
tessera-syntax = { path = "../tessera-syntax" }
