[package]
name = "tessera-syntax-fuzz"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[lib]
name = "fuzz_target"
path = "fuzz_target.rs"

[package.metadata]
cargo-fuzz = true

[dependencies]
tessera-syntax = { path = ".." }
arbitrary = { version = "1.3", features = ["derive"] }
libfuzzer-sys = { version = "0.4", features = ["link_libfuzzer"] }