//! Results -> Markdown summary. Generated from the same analysis structs as
//! the JSON, so the two cannot disagree. Contains no timestamps or paths.

use std::fmt::Write as _;

use crate::analysis;
use crate::bench::{Results, TOOL_NAME, VariantRecord};
use crate::corpus::{Lang, Status};
use crate::report_json::limitations;

fn short(id: &str) -> &str {
    id.rsplit('/').next().unwrap_or(id)
}

fn num(x: f64) -> String {
    if (x - x.round()).abs() < 1e-9 {
        format!("{x:.0}")
    } else {
        format!("{x:.1}")
    }
}

fn pct(x: f64) -> String {
    format!("{:.0}%", x * 100.0)
}

fn signed(n: i64) -> String {
    if n > 0 {
        format!("+{n}")
    } else {
        n.to_string()
    }
}

fn table(out: &mut String, headers: &[String], rows: &[Vec<String>]) {
    let _ = writeln!(out, "| {} |", headers.join(" | "));
    let _ = writeln!(
        out,
        "|{}|",
        headers.iter().map(|_| "---").collect::<Vec<_>>().join("|")
    );
    for row in rows {
        let _ = writeln!(out, "| {} |", row.join(" | "));
    }
    out.push('\n');
}

fn variant_label(v: &VariantRecord) -> String {
    match (v.lang, v.status) {
        (Lang::Tessera, Some(Status::Parsed)) => {
            format!("tessera {} [parsed]", v.candidate.as_deref().unwrap_or("?"))
        }
        (Lang::Tessera, _) => format!(
            "tessera {} [unparsed]",
            v.candidate.as_deref().unwrap_or("?")
        ),
        (lang, _) => lang.as_str().to_owned(),
    }
}

/// Render the Markdown report.
#[must_use]
pub fn to_markdown(r: &Results) -> String {
    let mut out = String::new();
    let measured = r.measured_ids();
    let tessera_total: usize = r
        .programs
        .iter()
        .flat_map(|p| p.variants.iter())
        .filter(|v| v.lang == Lang::Tessera)
        .count();
    let tessera_parsed: usize = r
        .programs
        .iter()
        .flat_map(|p| p.variants.iter())
        .filter(|v| v.is_parsed_tessera())
        .count();
    let variants: usize = r.programs.iter().map(|p| p.variants.len()).sum();

    let _ = writeln!(out, "# Tessera tokenizer benchmark results\n");
    let _ = writeln!(
        out,
        "Generated by `{TOOL_NAME}` (see `bench/README.md`). Do not edit; regenerate with the command in that file. Counts are deterministic for a fixed corpus and tokenizer set.\n"
    );

    let _ = writeln!(out, "## Provenance\n");
    let _ = writeln!(
        out,
        "- tool: `{TOOL_NAME}` {} (results schema 1)",
        env!("CARGO_PKG_VERSION")
    );
    let _ = writeln!(out, "- corpus_hash: `{}`", r.corpus_hash);
    let _ = writeln!(
        out,
        "- corpus_revision: {}",
        r.corpus_revision
            .as_deref()
            .map_or("not recorded".to_owned(), |s| format!("`{s}`"))
    );
    let _ = writeln!(
        out,
        "- corpus: {} programs, {variants} variants ({tessera_total} tessera: {tessera_parsed} parsed, {} unparsed)",
        r.programs.len(),
        tessera_total - tessera_parsed
    );
    let _ = writeln!(
        out,
        "- tokenizers measured: {} from {} vendor(s) ({}); skipped: {}\n",
        measured.len(),
        r.measured_vendors().len(),
        r.measured_vendors().join(", "),
        r.tokenizers.len() - measured.len()
    );
    let headers: Vec<String> = ["id", "vendor", "family", "status", "version / provenance"]
        .map(String::from)
        .to_vec();
    let rows: Vec<Vec<String>> = r
        .tokenizers
        .iter()
        .map(|t| {
            vec![
                format!("`{}`", t.id),
                t.vendor.clone(),
                t.family.clone(),
                if t.skipped.is_none() {
                    "measured".to_owned()
                } else {
                    "skipped".to_owned()
                },
                t.provenance.describe(),
            ]
        })
        .collect();
    table(&mut out, &headers, &rows);
    let skipped: Vec<_> = r
        .tokenizers
        .iter()
        .filter(|t| t.skipped.is_some())
        .collect();
    if !skipped.is_empty() {
        let _ = writeln!(out, "Skipped tokenizers (never silently omitted):\n");
        for t in skipped {
            let _ = writeln!(out, "- `{}`: {}", t.id, t.skipped.as_deref().unwrap_or(""));
        }
        out.push('\n');
    }

    let _ = writeln!(out, "## Metric definitions\n");
    for line in [
        "`bytes`, `nonws`: UTF-8 bytes and non-whitespace characters of the file (controls, tokenizer-independent). `lex`: Tessera lexer non-trivia tokens (tessera variants only).",
        "Token columns: model tokens per tokenizer (ordinary encoding, no special tokens). `median`/`worst`: over the measured tokenizers. `disp` = (worst - min) / median. `density` = semantic_units / median.",
        "Alignment (tessera variants): `intact` = grammar units with no model-token boundary inside; `exact` = units that are exactly one model token; `merged` = adjacent unit pairs covered by one model token.",
        "`[parsed]` = the current parser accepts the text with no diagnostics. `[unparsed]` = candidate spelling for a construct the parser does not implement; it is unvalidated text, not Tessera.",
    ] {
        let _ = writeln!(out, "- {line}");
    }
    out.push('\n');

    let _ = writeln!(out, "## Per-program results\n");
    let _ = writeln!(
        out,
        "semantic_units is defined in `bench/corpus/corpus.json`. Candidate labels are defined in `bench/README.md`.\n"
    );
    for p in &r.programs {
        let _ = writeln!(
            out,
            "### {} ({}, {} semantic units)\n",
            p.id, p.category, p.semantic_units
        );
        let _ = writeln!(out, "{} Units: {}.\n", p.description, p.semantic_units_note);
        let mut headers: Vec<String> = ["variant", "bytes", "nonws", "lex"]
            .map(String::from)
            .to_vec();
        headers.extend(measured.iter().map(|id| short(id).to_owned()));
        headers.extend(["median", "worst", "disp", "density"].map(String::from));
        let rows: Vec<Vec<String>> = p
            .variants
            .iter()
            .map(|v| {
                let mut row = vec![
                    variant_label(v),
                    v.bytes.to_string(),
                    v.non_ws_chars.to_string(),
                    v.lexer_tokens.map_or("-".to_owned(), |n| n.to_string()),
                ];
                row.extend(measured.iter().map(|id| {
                    v.tokens
                        .get(*id)
                        .map_or("-".to_owned(), ToString::to_string)
                }));
                match &v.stats {
                    Some(s) => row.extend([
                        num(s.median),
                        s.worst.to_string(),
                        format!("{:.2}", s.dispersion),
                        v.model_density
                            .map_or("-".to_owned(), |d| format!("{d:.3}")),
                    ]),
                    None => row.extend(std::iter::repeat_n("-".to_owned(), 4)),
                }
                row
            })
            .collect();
        table(&mut out, &headers, &rows);
    }

    let groups = analysis::groups(r);
    let _ = writeln!(out, "## Totals by language and candidate\n");
    let _ = writeln!(
        out,
        "Sum of model tokens over the programs each row has (`programs` column). Rows covering all programs are directly comparable; candidate rows B-G cover only programs that use their construct.\n"
    );
    let mut headers: Vec<String> = ["group", "programs", "bytes"].map(String::from).to_vec();
    headers.extend(measured.iter().map(|id| short(id).to_owned()));
    let rows: Vec<Vec<String>> = groups
        .iter()
        .map(|g| {
            let mut row = vec![
                format!("`{}`", g.name),
                g.programs.to_string(),
                g.bytes.to_string(),
            ];
            row.extend(measured.iter().map(|id| {
                g.tokens
                    .get(*id)
                    .map_or("-".to_owned(), ToString::to_string)
            }));
            row
        })
        .collect();
    table(&mut out, &headers, &rows);

    let vs = analysis::vs_anchor(r);
    let _ = writeln!(out, "## Candidates vs anchor A (same programs)\n");
    let _ = writeln!(
        out,
        "Each candidate is anchor A with exactly one substitution (see `bench/README.md`). Cells are candidate minus anchor token totals over the programs where the candidate exists (negative = cheaper than A). Every candidate here is `unparsed` text: even where A is `parsed`, B uses a function form the parser rejects.\n"
    );
    let mut headers: Vec<String> = ["candidate", "programs", "bytes A->X"]
        .map(String::from)
        .to_vec();
    headers.extend(measured.iter().map(|id| format!("d {}", short(id))));
    let rows: Vec<Vec<String>> = vs
        .iter()
        .map(|v| {
            let mut row = vec![
                v.candidate.clone(),
                v.programs.len().to_string(),
                format!(
                    "{} -> {} ({})",
                    v.anchor_bytes,
                    v.candidate_bytes,
                    signed(v.candidate_bytes as i64 - v.anchor_bytes as i64)
                ),
            ];
            row.extend(measured.iter().map(|id| {
                v.per_tokenizer.get(*id).map_or("-".to_owned(), |&(a, c)| {
                    format!("{} ({}->{})", signed(c as i64 - a as i64), a, c)
                })
            }));
            row
        })
        .collect();
    table(&mut out, &headers, &rows);

    let pairs = analysis::pairs(r);
    let _ = writeln!(out, "## Candidate pairs: does shorter mean cheaper?\n");
    let _ = writeln!(
        out,
        "Per program, each candidate vs anchor A. Bytes are the visual length; token cells are candidate minus anchor. Flags: `costlier` = candidate is shorter in bytes but costs MORE tokens; `no gain` = shorter in bytes, equal tokens; `longer-cheaper` = longer in bytes but FEWER tokens.\n"
    );
    let mut headers: Vec<String> = ["program", "cand", "bytes A/X"].map(String::from).to_vec();
    headers.extend(measured.iter().map(|id| format!("d {}", short(id))));
    headers.push("flags".to_owned());
    let rows: Vec<Vec<String>> = pairs
        .iter()
        .map(|p| {
            let mut row = vec![
                p.program.clone(),
                p.candidate.clone(),
                format!("{}/{}", p.anchor_bytes, p.candidate_bytes),
            ];
            row.extend(measured.iter().map(|id| {
                p.per_tokenizer
                    .get(*id)
                    .map_or("-".to_owned(), |&(a, c)| signed(c as i64 - a as i64))
            }));
            let mut flags = Vec::new();
            let costlier = p.shorter_but_costlier_on();
            if !costlier.is_empty() {
                flags.push(format!(
                    "costlier: {}",
                    costlier
                        .iter()
                        .map(|s| short(s))
                        .collect::<Vec<_>>()
                        .join(",")
                ));
            }
            let nogain = p.shorter_but_no_cheaper_on();
            if !nogain.is_empty() {
                flags.push(format!(
                    "no gain: {}",
                    nogain
                        .iter()
                        .map(|s| short(s))
                        .collect::<Vec<_>>()
                        .join(",")
                ));
            }
            let lc = p.longer_but_cheaper_on();
            if !lc.is_empty() {
                flags.push(format!(
                    "longer-cheaper: {}",
                    lc.iter().map(|s| short(s)).collect::<Vec<_>>().join(",")
                ));
            }
            row.push(if flags.is_empty() {
                "-".to_owned()
            } else {
                flags.join("; ")
            });
            row
        })
        .collect();
    table(&mut out, &headers, &rows);

    let _ = writeln!(out, "## Cross-tokenizer dispersion\n");
    let _ = writeln!(
        out,
        "Dispersion = (worst - min) / median over the measured tokenizers, per variant; summarized per group.\n"
    );
    let headers: Vec<String> = [
        "group",
        "variants",
        "mean disp",
        "max disp",
        "max at program",
    ]
    .map(String::from)
    .to_vec();
    let rows: Vec<Vec<String>> = groups
        .iter()
        .map(|g| {
            vec![
                format!("`{}`", g.name),
                g.programs.to_string(),
                format!("{:.2}", g.mean_dispersion),
                format!("{:.2}", g.max_dispersion),
                g.max_dispersion_program.clone(),
            ]
        })
        .collect();
    table(&mut out, &headers, &rows);

    let _ = writeln!(out, "## Grammar-boundary alignment (tessera variants)\n");
    let _ = writeln!(
        out,
        "Grammar units are the lexer's non-trivia tokens. Each cell: intact / exact / merged-with-neighbour, as percentages of summed units (merged: of summed adjacent pairs). One-character units are trivially intact; `exact` and `merged` are the more discriminating columns.\n"
    );
    let mut headers: Vec<String> = ["group", "variants", "units"].map(String::from).to_vec();
    headers.extend(measured.iter().map(|id| short(id).to_owned()));
    let rows: Vec<Vec<String>> = analysis::alignment_groups(r)
        .iter()
        .map(|g| {
            let units = g.per_tokenizer.values().next().map_or(0, |a| a.units);
            let mut row = vec![
                format!("`{}`", g.name),
                g.variants.to_string(),
                units.to_string(),
            ];
            row.extend(measured.iter().map(|id| {
                g.per_tokenizer.get(*id).map_or("-".to_owned(), |a| {
                    format!(
                        "{} / {} / {}",
                        pct(a.intact_fraction()),
                        pct(a.exact_fraction()),
                        pct(a.merged_fraction())
                    )
                })
            }));
            row
        })
        .collect();
    table(&mut out, &headers, &rows);

    let summary = analysis::rewrite_summary(r);
    let _ = writeln!(out, "## Rewrite stability (TOKDRIFT-style)\n");
    let rewrite_total: usize = r.rewrites.iter().map(|s| s.items.len()).sum();
    let layout: Vec<_> = summary
        .iter()
        .filter(|a| a.kind == crate::rewrite::RewriteKind::Layout)
        .collect();
    let layout_ok: usize = layout.iter().map(|a| a.collapsed_by_fmt).sum();
    let layout_total: usize = layout.iter().map(|a| a.variants).sum();
    let rename_ok: usize = summary
        .iter()
        .filter(|a| a.kind == crate::rewrite::RewriteKind::Rename)
        .map(|a| a.collapsed_by_fmt)
        .sum();
    let rename_total: usize = summary
        .iter()
        .filter(|a| a.kind == crate::rewrite::RewriteKind::Rename)
        .map(|a| a.variants)
        .sum();
    let _ = writeln!(
        out,
        "{rewrite_total} rewrites of {} parsed variants, every one validated against the parser. `tsr fmt` collapses {layout_ok}/{layout_total} layout rewrites (spaces, newlines, comments, redundant parentheses) to the single canonical spelling, and {rename_ok}/{rename_total} identifier renames (renames change the canonical text; a whitespace formatter cannot undo them).\n",
        r.rewrites.len()
    );
    let _ = writeln!(
        out,
        "Cell: variants whose token count is unchanged / variants, token delta range vs the canonical spelling, and grammar units whose segmentation changed / units compared (layout-only rewrites; `split` = units whose internal cuts changed, the rest changed only where a token boundary falls at the unit's edges, i.e. which neighbour it merges with). Stable means delta 0. Rewrites that add characters (comments, parentheses) cannot be stable; the point is the size of the drift and whether the same unit is split differently.\n"
    );
    let mut headers: Vec<String> = ["rewrite", "kind", "fmt collapses"]
        .map(String::from)
        .to_vec();
    headers.extend(measured.iter().map(|id| short(id).to_owned()));
    let rows: Vec<Vec<String>> = summary
        .iter()
        .map(|a| {
            let mut row = vec![
                format!("`{}`", a.name),
                a.kind.as_str().to_owned(),
                format!("{}/{}", a.collapsed_by_fmt, a.variants),
            ];
            row.extend(measured.iter().map(|id| {
                a.per_tokenizer.get(*id).map_or("-".to_owned(), |t| {
                    let range = if t.min_delta == t.max_delta {
                        signed(t.min_delta)
                    } else {
                        format!("{}..{}", signed(t.min_delta), signed(t.max_delta))
                    };
                    let reseg = if t.resegmented.1 > 0 {
                        format!(
                            ", reseg {}/{} (split {})",
                            t.resegmented.0, t.resegmented.1, t.split_changed
                        )
                    } else {
                        String::new()
                    };
                    format!("{}/{} stable, d {range}{reseg}", t.stable, t.total)
                })
            }));
            row
        })
        .collect();
    table(&mut out, &headers, &rows);

    let _ = writeln!(out, "## Limitations\n");
    for line in limitations(r) {
        let _ = writeln!(out, "- {line}");
    }
    out
}
